services:
  mssql: 
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name:  mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin12345!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_vol:/var/opt/mssql

volumes:
  mssql_vol:
    driver: local